#!/bin/bash

temp_file=/tmp/kwdb.tmp

# Create an array of all vfat mount points
mtarr=( `mount -t vfat | cut -f1,3 -d" "` )

num_array_elements=${#mtarr[*]}

echo -e "Please choose one of the following mount points (ctrl-c to exit):\n"
for ((index=0, mtpt=0; mtpt < num_array_elements; index++, mtpt+=2))
    do
        echo $index\) ${mtarr[@]:mtpt:2}
    done

echo -ne "\nPlease choose: "
read choice

device=${mtarr[((choice*2))]}
directory=${mtarr[((choice*2+1))]}
echo "You chose" $device "mounted at" $directory

# Check that the user has a .mtoolsrc file, and that it contains an entry for this device
if [ -e $HOME/.mtoolsrc ]; then
    echo "You have a .mtoolsrc file"
    # Check to see if the device appears in this file
    drive_letter=`grep $device $HOME/.mtoolsrc | cut -f2 -d" "`
else
    echo "You do not have a .mtoolsrc file - creating it"
    echo 'drive a: file="'$device'"' > $HOME/.mtoolsrc
    echo 'mtools_skip_check=1' >> $HOME/.mtoolsrc
    drive_letter=a:
fi

echo "Using mtools drive:" $drive_letter

sudo mdir -s $drive_letter > $temp_file

echo ./DapGen.py -m $temp_file $directory
